version: 2.1
jobs:
  release:
    steps:
      - checkout:
          path: ${{ repository.workspace }}
      - setup_python:
          python-version: 3.8
      - run: |
          python -m pip install -r requirements.txt
      - run: |
          python setup.py sdist bdist_wheel
      - run: |
          twine upload dist/*
