name: Deploy to PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Twine
      run: pip install twine

    - name: Create Distribution
      run: python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      run: twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.danangfir }}
        TWINE_PASSWORD: ${{ secrets.dancogpypi26 }}


